package com.messenger.phone.number.text.sms.service.apps.viewModel

import android.content.Context
import android.util.Log
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.messenger.phone.number.text.sms.service.apps.CommanClass.changelang
import com.messenger.phone.number.text.sms.service.apps.CommanClass.config
import com.messenger.phone.number.text.sms.service.apps.modelClass.Languagemodel
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class MessageLanguageViewModel @Inject constructor(@ApplicationContext var context: Context) : ViewModel() {

    val lanlist: ArrayList<Languagemodel> = arrayListOf()
    var lanlistmu = MutableLiveData<List<Languagemodel>>()
    val lanlistlive: LiveData<List<Languagemodel>>
        get() = lanlistmu
    var changelang = ""


    fun refreshdata() {

        viewModelScope.launch(Dispatchers.IO) {
            lanlist.clear()
            lanlistmu.postValue(arrayListOf())
//            lanlist.add(Languagemodel(language = "English", languagecode = "en", languagereal = "English"))
//            lanlist.add(Languagemodel(language = "हिन्दी", languagecode = "hi", languagereal = "Hindi"))
//            lanlist.add(Languagemodel(language = "Spanish", languagecode = "es", languagereal = "Española"))
//            lanlist.add(Languagemodel(language = "French", languagecode = "fr", languagereal = "Français"))
//            lanlist.add(Languagemodel(language = "Portuguese", languagecode = "pt", languagereal = "Português"))
//            lanlist.add(Languagemodel(language = "German", languagecode = "de", languagereal = "Deutsch"))
//            lanlist.add(Languagemodel(language = "Arabic", languagecode = "ar", languagereal = "عربي"))
//            lanlist.add(Languagemodel(language = "Japanese", languagecode = "ja", languagereal = "日本語"))
//            lanlist.add(Languagemodel(language = "Korean", languagecode = "ko", languagereal = "한국인"))
//            lanlist.add(Languagemodel(language = "Indonesian", languagecode = "in", languagereal = "bahasa Indonesia"))
//            lanlist.add(Languagemodel(language = "Swedish", languagecode = "sv", languagereal = "svenska"))
//            lanlist.add(Languagemodel(language = "Turkish", languagecode = "tr", languagereal = "Türkçe"))
//            lanlist.add(Languagemodel(language = "Gujarati", languagecode = "gu", languagereal = "ગુજરાતી"))
//            lanlist.add(Languagemodel(language = "Chinese", languagecode = "zh", languagereal = "中国人"))
//            lanlist.add(Languagemodel(language = "Russian", languagecode = "ru", languagereal = "Русский"))
//            lanlist.add(Languagemodel(language = "Tamil", languagecode = "ta", languagereal = "தமிழ்"))
//            lanlist.add(Languagemodel(language = "Telugu", languagecode = "te", languagereal = "తెలుగు"))


//            lanlist.add(Languagemodel(language = "Afrikaans", languagecode = "af", languagereal = "Afrikaans"))
//            lanlist.add(Languagemodel(language = "Albanian", languagecode = "sq", languagereal = "Shqip"))
//            lanlist.add(Languagemodel(language = "Amharic", languagecode = "am", languagereal = "አማርኛ"))
//            lanlist.add(Languagemodel(language = "Arabic", languagecode = "ar", languagereal = "العربية"))
//            lanlist.add(Languagemodel(language = "Armenian", languagecode = "hy", languagereal = "Հայերեն"))
//            lanlist.add(Languagemodel(language = "Assamese", languagecode = "as", languagereal = "অসমীয়া"))
//            lanlist.add(Languagemodel(language = "Aymara", languagecode = "ay", languagereal = "Aymar"))
//            lanlist.add(Languagemodel(language = "Azerbaijani", languagecode = "az", languagereal = "Azərbaycan dili"))
//            lanlist.add(Languagemodel(language = "Bambara", languagecode = "bm", languagereal = "Bamanankan"))
//            lanlist.add(Languagemodel(language = "Basque", languagecode = "eu", languagereal = "Euskara"))
//            lanlist.add(Languagemodel(language = "Belarusian", languagecode = "be", languagereal = "Беларуская"))
//            lanlist.add(Languagemodel(language = "Bengali", languagecode = "bn", languagereal = "বাংলা"))
//            lanlist.add(Languagemodel(language = "Bhojpuri", languagecode = "bh", languagereal = "भोजपुरी"))
//            lanlist.add(Languagemodel(language = "Bosnian", languagecode = "bs", languagereal = "Bosanski"))
//            lanlist.add(Languagemodel(language = "Bulgarian", languagecode = "bg", languagereal = "Български"))
//            lanlist.add(Languagemodel(language = "Catalan", languagecode = "ca", languagereal = "Català"))
//            lanlist.add(Languagemodel(language = "Cebuano", languagecode = "ceb", languagereal = "Cebuano"))
//            lanlist.add(Languagemodel(language = "Chichewa", languagecode = "ny", languagereal = "Chichewa"))
//            lanlist.add(Languagemodel(language = "Chinese (Simplified)", languagecode = "zh-CN", languagereal = "简体中文"))
//            lanlist.add(Languagemodel(language = "Chinese (Traditional)", languagecode = "zh-TW", languagereal = "繁體中文"))
//            lanlist.add(Languagemodel(language = "Corsican", languagecode = "co", languagereal = "Corsu"))
//            lanlist.add(Languagemodel(language = "Croatian", languagecode = "hr", languagereal = "Hrvatski"))
//            lanlist.add(Languagemodel(language = "Czech", languagecode = "cs", languagereal = "Čeština"))
//            lanlist.add(Languagemodel(language = "Danish", languagecode = "da", languagereal = "Dansk"))
//            lanlist.add(Languagemodel(language = "Danish", languagecode = "da", languagereal = "Dansk"))
//            lanlist.add(Languagemodel(language = "Dhivehi", languagecode = "dv", languagereal = "ދިވެހި"))
//            lanlist.add(Languagemodel(language = "Dogri", languagecode = "doi", languagereal = "डोगरी"))
//            lanlist.add(Languagemodel(language = "Dutch", languagecode = "nl", languagereal = "Nederlands"))
//            lanlist.add(Languagemodel(language = "Esperanto", languagecode = "eo", languagereal = "Esperanto"))
//            lanlist.add(Languagemodel(language = "Estonian", languagecode = "et", languagereal = "Eesti"))
//            lanlist.add(Languagemodel(language = "Ewe", languagecode = "ee", languagereal = "Ɛʋɛ"))
//            lanlist.add(Languagemodel(language = "Filipino", languagecode = "fil", languagereal = "Filipino"))
//            lanlist.add(Languagemodel(language = "Finnish", languagecode = "fi", languagereal = "Suomi"))
//            lanlist.add(Languagemodel(language = "French", languagecode = "fr", languagereal = "Français"))
//            lanlist.add(Languagemodel(language = "Frisian", languagecode = "fy", languagereal = "Frysk"))
//            lanlist.add(Languagemodel(language = "Galician", languagecode = "gl", languagereal = "Galego"))
//            lanlist.add(Languagemodel(language = "Georgian", languagecode = "ka", languagereal = "ქართული"))
//            lanlist.add(Languagemodel(language = "German", languagecode = "de", languagereal = "Deutsch"))
//            lanlist.add(Languagemodel(language = "Greek", languagecode = "el", languagereal = "Ελληνικά"))
//            lanlist.add(Languagemodel(language = "Guarani", languagecode = "gn", languagereal = "Avañe'ẽ"))
//            lanlist.add(Languagemodel(language = "History", languagecode = "history", languagereal = "History"))
//            lanlist.add(Languagemodel(language = "Gujarati", languagecode = "gu", languagereal = "Gujarati"))
//            lanlist.add(Languagemodel(language = "Haitian Creole", languagecode = "ht", languagereal = "Kreyòl Ayisyen"))
//            lanlist.add(Languagemodel(language = "Hausa", languagecode = "ha", languagereal = "Hausa"))
//            lanlist.add(Languagemodel(language = "Hawaiian", languagecode = "haw", languagereal = "ʻŌlelo Hawaiʻi"))
//            lanlist.add(Languagemodel(language = "Hebrew", languagecode = "he", languagereal = "עברית"))
//            lanlist.add(Languagemodel(language = "हिन्दी", languagecode = "hi", languagereal = "Hindi"))
//            lanlist.add(Languagemodel(language = "Hmong", languagecode = "hmn", languagereal = "Hmoob"))
//            lanlist.add(Languagemodel(language = "Hungarian", languagecode = "hu", languagereal = "Magyar"))
//            lanlist.add(Languagemodel(language = "Icelandic", languagecode = "is", languagereal = "Íslenska"))
//            lanlist.add(Languagemodel(language = "Igbo", languagecode = "ig", languagereal = "Igbo"))
//            lanlist.add(Languagemodel(language = "Ilocano", languagecode = "ilo", languagereal = "Ilokano"))
//            lanlist.add(Languagemodel(language = "Indonesian", languagecode = "id", languagereal = "Bahasa Indonesia"))
//            lanlist.add(Languagemodel(language = "Irish", languagecode = "ga", languagereal = "Gaeilge"))
//            lanlist.add(Languagemodel(language = "Italian", languagecode = "it", languagereal = "Italiano"))
//            lanlist.add(Languagemodel(language = "Japanese", languagecode = "ja", languagereal = "日本語"))
//            lanlist.add(Languagemodel(language = "Javanese", languagecode = "jv", languagereal = "Basa Jawa"))
//            lanlist.add(Languagemodel(language = "Kannada", languagecode = "kn", languagereal = "ಕನ್ನಡ"))
//            lanlist.add(Languagemodel(language = "Kazakh", languagecode = "kk", languagereal = "Қазақ тілі"))
//            lanlist.add(Languagemodel(language = "Khmer", languagecode = "km", languagereal = "ភាសាខ្មែរ"))
//            lanlist.add(Languagemodel(language = "Kinyarwanda", languagecode = "rw", languagereal = "Kinyarwanda"))
//            lanlist.add(Languagemodel(language = "Konkani", languagecode = "kok", languagereal = "कोंकणी"))
//            lanlist.add(Languagemodel(language = "Korean", languagecode = "ko", languagereal = "한국어"))
//            lanlist.add(Languagemodel(language = "Krio", languagecode = "kri", languagereal = "Krio"))
//            lanlist.add(Languagemodel(language = "Kurdish (Kurmanji)", languagecode = "ku", languagereal = "Kurdî (Kurmancî)"))
//            lanlist.add(Languagemodel(language = "Kurdish (Sorani)", languagecode = "ckb", languagereal = "کوردی (کورمانجی)"))
//            lanlist.add(Languagemodel(language = "Kyrgyz", languagecode = "ky", languagereal = "Кыргызча"))
//            lanlist.add(Languagemodel(language = "Lao", languagecode = "lo", languagereal = "ພາສາລາວ"))
//            lanlist.add(Languagemodel(language = "Latin", languagecode = "la", languagereal = "Latina"))
//            lanlist.add(Languagemodel(language = "Latvian", languagecode = "lv", languagereal = "Latviešu"))
//            lanlist.add(Languagemodel(language = "Lingala", languagecode = "ln", languagereal = "Lingála"))
//            lanlist.add(Languagemodel(language = "Lithuanian", languagecode = "lt", languagereal = "Lietuvių"))
//            lanlist.add(Languagemodel(language = "Luganda", languagecode = "lg", languagereal = "Luganda"))
//            lanlist.add(Languagemodel(language = "Luxembourgish", languagecode = "lb", languagereal = "Lëtzebuergesch"))
//            lanlist.add(Languagemodel(language = "Macedonian", languagecode = "mk", languagereal = "Македонски"))
//            lanlist.add(Languagemodel(language = "Maithili", languagecode = "mai", languagereal = "मैथिली"))
//            lanlist.add(Languagemodel(language = "Malagasy", languagecode = "mg", languagereal = "Malagasy"))
//            lanlist.add(Languagemodel(language = "Malay", languagecode = "ms", languagereal = "Bahasa Melayu"))
//            lanlist.add(Languagemodel(language = "Malayalam", languagecode = "ml", languagereal = "മലയാളം"))
//            lanlist.add(Languagemodel(language = "Maltese", languagecode = "mt", languagereal = "Malti"))
//            lanlist.add(Languagemodel(language = "Maori", languagecode = "mi", languagereal = "Te Reo Māori"))
//            lanlist.add(Languagemodel(language = "Marathi", languagecode = "mr", languagereal = "मराठी"))
//            lanlist.add(Languagemodel(language = "Meiteilon (Manipuri)", languagecode = "mni", languagereal = "মৈতৈলোন্"))
//            lanlist.add(Languagemodel(language = "Mizo", languagecode = "lus", languagereal = "Lushai"))
//            lanlist.add(Languagemodel(language = "Mongolian", languagecode = "mn", languagereal = "Монгол"))
//            lanlist.add(Languagemodel(language = "Myanmar (Burmese)", languagecode = "my", languagereal = "ဗမာစာ"))
//            lanlist.add(Languagemodel(language = "Nepali", languagecode = "ne", languagereal = "नेपाली"))
//            lanlist.add(Languagemodel(language = "Norwegian", languagecode = "no", languagereal = "Norsk"))
//            lanlist.add(Languagemodel(language = "Odia (Oriya)", languagecode = "or", languagereal = "ଓଡ଼ିଆ"))
//            lanlist.add(Languagemodel(language = "Oromo", languagecode = "om", languagereal = "Oromoo"))
//            lanlist.add(Languagemodel(language = "Pashto", languagecode = "ps", languagereal = "پښتو"))
//            lanlist.add(Languagemodel(language = "Persian", languagecode = "fa", languagereal = "فارسی"))
//            lanlist.add(Languagemodel(language = "Polish", languagecode = "pl", languagereal = "Polski"))
//            lanlist.add(Languagemodel(language = "Portuguese", languagecode = "pt", languagereal = "Português"))
//            lanlist.add(Languagemodel(language = "Punjabi", languagecode = "pa", languagereal = "ਪੰਜਾਬੀ"))
//            lanlist.add(Languagemodel(language = "Quechua", languagecode = "qu", languagereal = "Runa Simi"))
//            lanlist.add(Languagemodel(language = "Romanian", languagecode = "ro", languagereal = "Română"))
//            lanlist.add(Languagemodel(language = "Russian", languagecode = "ru", languagereal = "Русский"))
//            lanlist.add(Languagemodel(language = "Samoan", languagecode = "sm", languagereal = "Gagana Samoa"))
//            lanlist.add(Languagemodel(language = "Sanskrit", languagecode = "sa", languagereal = "संस्कृतम्"))
//            lanlist.add(Languagemodel(language = "Scots Gaelic", languagecode = "gd", languagereal = "Gàidhlig"))
//            lanlist.add(Languagemodel(language = "Sepedi", languagecode = "nso", languagereal = "Sesotho sa Leboa"))
//            lanlist.add(Languagemodel(language = "Serbian", languagecode = "sr", languagereal = "Српски"))
//            lanlist.add(Languagemodel(language = "Sesotho", languagecode = "st", languagereal = "Sesotho"))
//            lanlist.add(Languagemodel(language = "Shona", languagecode = "sn", languagereal = "ChiShona"))
//            lanlist.add(Languagemodel(language = "Sindhi", languagecode = "sd", languagereal = "سنڌي"))
//            lanlist.add(Languagemodel(language = "Sinhala", languagecode = "si", languagereal = "සිංහල"))
//            lanlist.add(Languagemodel(language = "Slovak", languagecode = "sk", languagereal = "Slovenčina"))
//            lanlist.add(Languagemodel(language = "Slovenian", languagecode = "sl", languagereal = "Slovenščina"))
//            lanlist.add(Languagemodel(language = "Somali", languagecode = "so", languagereal = "Soomaali"))
//            lanlist.add(Languagemodel(language = "Spanish", languagecode = "es", languagereal = "Español"))
//            lanlist.add(Languagemodel(language = "Sundanese", languagecode = "su", languagereal = "Basa Sunda"))
//            lanlist.add(Languagemodel(language = "Swahili", languagecode = "sw", languagereal = "Kiswahili"))
//            lanlist.add(Languagemodel(language = "Swedish", languagecode = "sv", languagereal = "Svenska"))
//            lanlist.add(Languagemodel(language = "Tajik", languagecode = "tg", languagereal = "тоҷикӣ"))
//            lanlist.add(Languagemodel(language = "Tamil", languagecode = "ta", languagereal = "தமிழ்"))
//            lanlist.add(Languagemodel(language = "Tatar", languagecode = "tt", languagereal = "Татарча"))
//            lanlist.add(Languagemodel(language = "Telugu", languagecode = "te", languagereal = "తెలుగు"))
//            lanlist.add(Languagemodel(language = "Thai", languagecode = "th", languagereal = "ไทย"))
//            lanlist.add(Languagemodel(language = "Tigrinya", languagecode = "ti", languagereal = "ትግርኛ"))
//            lanlist.add(Languagemodel(language = "Tsonga", languagecode = "ts", languagereal = "Xitsonga"))
//            lanlist.add(Languagemodel(language = "Turkish", languagecode = "tr", languagereal = "Türkçe"))
//            lanlist.add(Languagemodel(language = "Turkmen", languagecode = "tk", languagereal = "Türkmençe"))
//            lanlist.add(Languagemodel(language = "Twi", languagecode = "tw", languagereal = "Twi"))
//            lanlist.add(Languagemodel(language = "Ukrainian", languagecode = "uk", languagereal = "Українська"))
//            lanlist.add(Languagemodel(language = "Urdu", languagecode = "ur", languagereal = "اردو"))
//            lanlist.add(Languagemodel(language = "Uyghur", languagecode = "ug", languagereal = "Uyƣurqə"))
//            lanlist.add(Languagemodel(language = "Uzbek", languagecode = "uz", languagereal = "Oʻzbekcha"))
//            lanlist.add(Languagemodel(language = "Vietnamese", languagecode = "vi", languagereal = "Tiếng Việt"))
//            lanlist.add(Languagemodel(language = "Welsh", languagecode = "cy", languagereal = "Cymraeg"))
//            lanlist.add(Languagemodel(language = "Xhosa", languagecode = "xh", languagereal = "isiXhosa"))
//            lanlist.add(Languagemodel(language = "Yiddish", languagecode = "yi", languagereal = "ייִדיש"))
//            lanlist.add(Languagemodel(language = "Yoruba", languagecode = "yo", languagereal = "Yorùbá"))
//            lanlist.add(Languagemodel(language = "Zulu", languagecode = "zu", languagereal = "isiZulu"))


            lanlist.add(Languagemodel(language = "English", languagecode = "en", languagereal = "English"))
            lanlist.add(Languagemodel(language = "Hindi", languagecode = "hi", languagereal = "हिन्दी"))
            lanlist.add(Languagemodel(language = "Gujarati", languagecode = "gu", languagereal = "ગુજરાતી"))
            lanlist.add(Languagemodel(language = "Abkhaz", languagecode = "ab", languagereal = "Аҧсуа"))
            lanlist.add(Languagemodel(language = "Acehnese", languagecode = "ace", languagereal = "Aceh"))
            lanlist.add(Languagemodel(language = "Acholi", languagecode = "ach", languagereal = "Acholi"))
            lanlist.add(Languagemodel(language = "Afar", languagecode = "aa", languagereal = "Afar"))
            lanlist.add(Languagemodel(language = "Afrikaans", languagecode = "af", languagereal = "Afrikaans"))
            lanlist.add(Languagemodel(language = "Albanian", languagecode = "sq", languagereal = "Shqip"))
            lanlist.add(Languagemodel(language = "Alur", languagecode = "aln", languagereal = "Alur"))
            lanlist.add(Languagemodel(language = "Amharic", languagecode = "am", languagereal = "አማርኛ"))
            lanlist.add(Languagemodel(language = "Arabic", languagecode = "ar", languagereal = "العربية"))
            lanlist.add(Languagemodel(language = "Armenian", languagecode = "hy", languagereal = "Հայերեն"))
            lanlist.add(Languagemodel(language = "Assamese", languagecode = "as", languagereal = "অসমীয়া"))
            lanlist.add(Languagemodel(language = "Avar", languagecode = "av", languagereal = "Авар"))
            lanlist.add(Languagemodel(language = "Awadhi", languagecode = "awa", languagereal = "अवधी"))
            lanlist.add(Languagemodel(language = "Aymara", languagecode = "ay", languagereal = "Aymara"))
            lanlist.add(Languagemodel(language = "Azerbaijani", languagecode = "az", languagereal = "Azərbaycan dili"))
            lanlist.add(Languagemodel(language = "Balinese", languagecode = "ban", languagereal = "Basa Bali"))
            lanlist.add(Languagemodel(language = "Baluchi", languagecode = "bal", languagereal = "بلوچی"))
            lanlist.add(Languagemodel(language = "Bambara", languagecode = "bm", languagereal = "Bamanankan"))
            lanlist.add(Languagemodel(language = "Baoulé", languagecode = "bao", languagereal = "Baoulé"))
            lanlist.add(Languagemodel(language = "Bashkir", languagecode = "ba", languagereal = "Башҡорт"))
            lanlist.add(Languagemodel(language = "Basque", languagecode = "eu", languagereal = "Euskara"))
            lanlist.add(Languagemodel(language = "Batak Karo", languagecode = "btk", languagereal = "Batak Karo"))
            lanlist.add(Languagemodel(language = "Batak Simalungun", languagecode = "bts", languagereal = "Batak Simalungun"))
            lanlist.add(Languagemodel(language = "Batak Toba", languagecode = "bto", languagereal = "Batak Toba"))
            lanlist.add(Languagemodel(language = "Belarusian", languagecode = "be", languagereal = "Беларуская"))
            lanlist.add(Languagemodel(language = "Bemba", languagecode = "bem", languagereal = "Bemba"))
            lanlist.add(Languagemodel(language = "Bengali", languagecode = "bn", languagereal = "বাংলা"))
            lanlist.add(Languagemodel(language = "Betawi", languagecode = "bew", languagereal = "Betawi"))
            lanlist.add(Languagemodel(language = "Bhojpuri", languagecode = "bho", languagereal = "भोजपुरी"))
            lanlist.add(Languagemodel(language = "Bikol", languagecode = "bik", languagereal = "Bikol"))
            lanlist.add(Languagemodel(language = "Bosnian", languagecode = "bs", languagereal = "Bosanski"))
            lanlist.add(Languagemodel(language = "Breton", languagecode = "br", languagereal = "Brezhoneg"))
            lanlist.add(Languagemodel(language = "Bulgarian", languagecode = "bg", languagereal = "Български"))
            lanlist.add(Languagemodel(language = "Buryat", languagecode = "bxr", languagereal = "Буряад"))
            lanlist.add(Languagemodel(language = "Cantonese", languagecode = "yue", languagereal = "廣東話"))
            lanlist.add(Languagemodel(language = "Catalan", languagecode = "ca", languagereal = "Català"))
            lanlist.add(Languagemodel(language = "Cebuano", languagecode = "ceb", languagereal = "Cebuano"))
            lanlist.add(Languagemodel(language = "Chamorro", languagecode = "ch", languagereal = "Chamoru"))
            lanlist.add(Languagemodel(language = "Chechen", languagecode = "ce", languagereal = "Нохчийн"))
            lanlist.add(Languagemodel(language = "Chichewa", languagecode = "ny", languagereal = "Chichewa"))
            lanlist.add(Languagemodel(language = "Chinese (Simplified)", languagecode = "zh-CN", languagereal = "简体中文"))
            lanlist.add(Languagemodel(language = "Chinese (Traditional)", languagecode = "zh-TW", languagereal = "繁體中文"))
            lanlist.add(Languagemodel(language = "Chuukese", languagecode = "chk", languagereal = "Chuukese"))
            lanlist.add(Languagemodel(language = "Chuvash", languagecode = "cv", languagereal = "Чӳваш"))
            lanlist.add(Languagemodel(language = "Corsican", languagecode = "co", languagereal = "Corsu"))
            lanlist.add(Languagemodel(language = "Crimean Tatar (Cyrillic)", languagecode = "crh-cyrl", languagereal = "Qırımtatarca"))
            lanlist.add(Languagemodel(language = "Crimean Tatar (Latin)", languagecode = "crh-latn", languagereal = "Qırımtatarca"))
            lanlist.add(Languagemodel(language = "Croatian", languagecode = "hr", languagereal = "Hrvatski"))
            lanlist.add(Languagemodel(language = "Czech", languagecode = "cs", languagereal = "Čeština"))
            lanlist.add(Languagemodel(language = "Danish", languagecode = "da", languagereal = "Dansk"))
            lanlist.add(Languagemodel(language = "Dari", languagecode = "fa-AF", languagereal = "دری"))
            lanlist.add(Languagemodel(language = "Dhivehi", languagecode = "dv", languagereal = "ދިވެހި"))
            lanlist.add(Languagemodel(language = "Dinka", languagecode = "din", languagereal = "Dinka"))
            lanlist.add(Languagemodel(language = "Dogri", languagecode = "doi", languagereal = "डोगरी"))
            lanlist.add(Languagemodel(language = "Dombe", languagecode = "dmb", languagereal = "Dɔmbɛ"))
            lanlist.add(Languagemodel(language = "Dutch", languagecode = "nl", languagereal = "Nederlands"))
            lanlist.add(Languagemodel(language = "Dyula", languagecode = "dyu", languagereal = "Jula"))
            lanlist.add(Languagemodel(language = "Dzongkha", languagecode = "dz", languagereal = "རྫོང་ཁ"))
            lanlist.add(Languagemodel(language = "Esperanto", languagecode = "eo", languagereal = "Esperanto"))
            lanlist.add(Languagemodel(language = "Estonian", languagecode = "et", languagereal = "Eesti"))
            lanlist.add(Languagemodel(language = "Ewe", languagecode = "ee", languagereal = "Eʋegbe"))
            lanlist.add(Languagemodel(language = "Faroese", languagecode = "fo", languagereal = "Føroyskt"))
            lanlist.add(Languagemodel(language = "Fijian", languagecode = "fj", languagereal = "Na vosa Vakaviti"))
            lanlist.add(Languagemodel(language = "Filipino", languagecode = "fil", languagereal = "Filipino"))
            lanlist.add(Languagemodel(language = "Finnish", languagecode = "fi", languagereal = "Suomi"))
            lanlist.add(Languagemodel(language = "Fon", languagecode = "fon", languagereal = "Fon"))
            lanlist.add(Languagemodel(language = "French", languagecode = "fr", languagereal = "Français"))
            lanlist.add(Languagemodel(language = "French (Canada)", languagecode = "fr-CA", languagereal = "Français (Canada)"))
            lanlist.add(Languagemodel(language = "Frisian", languagecode = "fy", languagereal = "Frysk"))
            lanlist.add(Languagemodel(language = "Friulian", languagecode = "fur", languagereal = "Furlan"))
            lanlist.add(Languagemodel(language = "Fulani", languagecode = "ff", languagereal = "Fulfulde"))
            lanlist.add(Languagemodel(language = "Ga", languagecode = "gaa", languagereal = "Ga"))
            lanlist.add(Languagemodel(language = "Galician", languagecode = "gl", languagereal = "Galego"))
            lanlist.add(Languagemodel(language = "Georgian", languagecode = "ka", languagereal = "ქართული"))
            lanlist.add(Languagemodel(language = "German", languagecode = "de", languagereal = "Deutsch"))
            lanlist.add(Languagemodel(language = "Greek", languagecode = "el", languagereal = "Ελληνικά"))
            lanlist.add(Languagemodel(language = "Guarani", languagecode = "gn", languagereal = "Ava-guaraní"))
            lanlist.add(Languagemodel(language = "Haitian Creole", languagecode = "ht", languagereal = "Kreyòl Ayisyen"))
            lanlist.add(Languagemodel(language = "Hakha Chin", languagecode = "hch", languagereal = "Hakha Chin"))
            lanlist.add(Languagemodel(language = "Hausa", languagecode = "ha", languagereal = "Hausa"))
            lanlist.add(Languagemodel(language = "Hawaiian", languagecode = "haw", languagereal = "ʻŌlelo Hawaiʻi"))
            lanlist.add(Languagemodel(language = "Hebrew", languagecode = "he", languagereal = "עברית"))
            lanlist.add(Languagemodel(language = "Hiligaynon", languagecode = "hil", languagereal = "Hiligaynon"))
            lanlist.add(Languagemodel(language = "Hmong", languagecode = "hmn", languagereal = "Hmoob"))
            lanlist.add(Languagemodel(language = "Hungarian", languagecode = "hu", languagereal = "Magyar"))
            lanlist.add(Languagemodel(language = "Hunsrik", languagecode = "hsb", languagereal = "Hunsrückisch"))
            lanlist.add(Languagemodel(language = "Iban", languagecode = "iba", languagereal = "Iban"))
            lanlist.add(Languagemodel(language = "Icelandic", languagecode = "is", languagereal = "Íslenska"))
            lanlist.add(Languagemodel(language = "Igbo", languagecode = "ig", languagereal = "Igbo"))
            lanlist.add(Languagemodel(language = "Ilocano", languagecode = "ilo", languagereal = "Ilocano"))
            lanlist.add(Languagemodel(language = "Indonesian", languagecode = "id", languagereal = "Bahasa Indonesia"))
            lanlist.add(Languagemodel(language = "Inuktut (Latin)", languagecode = "iku-Latn", languagereal = "Inuktut"))
            lanlist.add(Languagemodel(language = "Inuktut (Syllabics)", languagecode = "iku", languagereal = "ᐃᓄᒃᑐᑦ"))
            lanlist.add(Languagemodel(language = "Irish", languagecode = "ga", languagereal = "Gaeilge"))
            lanlist.add(Languagemodel(language = "Italian", languagecode = "it", languagereal = "Italiano"))
            lanlist.add(Languagemodel(language = "Jamaican Patois", languagecode = "jm", languagereal = "Jamaican Patois"))
            lanlist.add(Languagemodel(language = "Japanese", languagecode = "ja", languagereal = "日本語"))
            lanlist.add(Languagemodel(language = "Javanese", languagecode = "jv", languagereal = "Basa Jawa"))
            lanlist.add(Languagemodel(language = "Jingpo", languagecode = "jgo", languagereal = "Jingpho"))
            lanlist.add(Languagemodel(language = "Kalaallisut", languagecode = "kl", languagereal = "Kalaallisut"))
            lanlist.add(Languagemodel(language = "Kannada", languagecode = "kn", languagereal = "ಕನ್ನಡ"))
            lanlist.add(Languagemodel(language = "Kanuri", languagecode = "kr", languagereal = "Kanuri"))
            lanlist.add(Languagemodel(language = "Kapampangan", languagecode = "pam", languagereal = "Kapampangan"))
            lanlist.add(Languagemodel(language = "Kazakh", languagecode = "kk", languagereal = "Қазақ тілі"))
            lanlist.add(Languagemodel(language = "Khasi", languagecode = "kha", languagereal = "Khasi"))
            lanlist.add(Languagemodel(language = "Khmer", languagecode = "km", languagereal = "ភាសាខ្មែរ"))
            lanlist.add(Languagemodel(language = "Kiga", languagecode = "kig", languagereal = "Kiga"))
            lanlist.add(Languagemodel(language = "Kikongo", languagecode = "kg", languagereal = "Kikongo"))
            lanlist.add(Languagemodel(language = "Kinyarwanda", languagecode = "rw", languagereal = "Kinyarwanda"))
            lanlist.add(Languagemodel(language = "Kituba", languagecode = "kgp", languagereal = "Kituba"))
            lanlist.add(Languagemodel(language = "Kokborok", languagecode = "kok", languagereal = "Kokborok"))
            lanlist.add(Languagemodel(language = "Komi", languagecode = "kv", languagereal = "Коми"))
            lanlist.add(Languagemodel(language = "Konkani", languagecode = "kok", languagereal = "कोंकणी"))
            lanlist.add(Languagemodel(language = "Korean", languagecode = "ko", languagereal = "한국어"))
            lanlist.add(Languagemodel(language = "Krio", languagecode = "crr", languagereal = "Krio"))
            lanlist.add(Languagemodel(language = "Kurdish (Kurmanji)", languagecode = "ku", languagereal = "Kurdî (Kurmanjî)"))
            lanlist.add(Languagemodel(language = "Kurdish (Sorani)", languagecode = "ckb", languagereal = "Kurdî (Sorânî)"))
            lanlist.add(Languagemodel(language = "Kyrgyz", languagecode = "ky", languagereal = "Кыргыз тили"))
            lanlist.add(Languagemodel(language = "Lao", languagecode = "lo", languagereal = "ລາວ"))
            lanlist.add(Languagemodel(language = "Latgalian", languagecode = "ltg", languagereal = "Latgalīšu"))
            lanlist.add(Languagemodel(language = "Latin", languagecode = "la", languagereal = "Latina"))
            lanlist.add(Languagemodel(language = "Latvian", languagecode = "lv", languagereal = "Latviešu"))
            lanlist.add(Languagemodel(language = "Ligurian", languagecode = "lij", languagereal = "Ligure"))
            lanlist.add(Languagemodel(language = "Limburgish", languagecode = "li", languagereal = "Limburgs"))
            lanlist.add(Languagemodel(language = "Lingala", languagecode = "ln", languagereal = "Lingála"))
            lanlist.add(Languagemodel(language = "Lithuanian", languagecode = "lt", languagereal = "Lietuvių"))
            lanlist.add(Languagemodel(language = "Lombard", languagecode = "lmo", languagereal = "Lombard"))
            lanlist.add(Languagemodel(language = "Luganda", languagecode = "lg", languagereal = "Luganda"))
            lanlist.add(Languagemodel(language = "Luo", languagecode = "luo", languagereal = "Luo"))
            lanlist.add(Languagemodel(language = "Luxembourgish", languagecode = "lb", languagereal = "Lëtzebuergesch"))
            lanlist.add(Languagemodel(language = "Macedonian", languagecode = "mk", languagereal = "Македонски"))
            lanlist.add(Languagemodel(language = "Madurese", languagecode = "mad", languagereal = "Madhurâ"))
            lanlist.add(Languagemodel(language = "Maithili", languagecode = "mai", languagereal = "मैथिली"))
            lanlist.add(Languagemodel(language = "Makassar", languagecode = "mak", languagereal = "Makasar"))
            lanlist.add(Languagemodel(language = "Malagasy", languagecode = "mg", languagereal = "Malagasy"))
            lanlist.add(Languagemodel(language = "Malay", languagecode = "ms", languagereal = "Melayu"))
            lanlist.add(Languagemodel(language = "Malay (Jawi)", languagecode = "ms-Arab", languagereal = "مالاي"))
            lanlist.add(Languagemodel(language = "Malayalam", languagecode = "ml", languagereal = "മലയാളം"))
            lanlist.add(Languagemodel(language = "Maltese", languagecode = "mt", languagereal = "Malti"))
            lanlist.add(Languagemodel(language = "Mam", languagecode = "mam", languagereal = "Mam"))
            lanlist.add(Languagemodel(language = "Manx", languagecode = "gv", languagereal = "Gaelg"))
            lanlist.add(Languagemodel(language = "Maori", languagecode = "mi", languagereal = "Te Reo Māori"))
            lanlist.add(Languagemodel(language = "Marathi", languagecode = "mr", languagereal = "मराठी"))
            lanlist.add(Languagemodel(language = "Marshallese", languagecode = "mh", languagereal = "Kajin Majõl"))
            lanlist.add(Languagemodel(language = "Marwadi", languagecode = "mwr", languagereal = "मारवाड़ी"))
            lanlist.add(Languagemodel(language = "Mauritian Creole", languagecode = "mfe", languagereal = "Kreol Morisien"))
            lanlist.add(Languagemodel(language = "Meadow Mari", languagecode = "mrj", languagereal = "Марий йылме"))
            lanlist.add(Languagemodel(language = "Meiteilon (Manipuri)", languagecode = "mni", languagereal = "মণিপুরী"))
            lanlist.add(Languagemodel(language = "Minang", languagecode = "min", languagereal = "Minangkabau"))
            lanlist.add(Languagemodel(language = "Mizo", languagecode = "mzo", languagereal = "Mizo"))
            lanlist.add(Languagemodel(language = "Mongolian", languagecode = "mn", languagereal = "Монгол хэл"))
            lanlist.add(Languagemodel(language = "Myanmar (Burmese)", languagecode = "my", languagereal = "မြန်မာဘာသာ"))
            lanlist.add(Languagemodel(language = "Nahuatl (Eastern Huasteca)", languagecode = "nah", languagereal = "Náhuatl"))
            lanlist.add(Languagemodel(language = "Ndau", languagecode = "ndu", languagereal = "ChiNdau"))
            lanlist.add(Languagemodel(language = "Ndebele (South)", languagecode = "nr", languagereal = "isiNdebele"))
            lanlist.add(Languagemodel(language = "Nepalbhasa (Newari)", languagecode = "new", languagereal = "नेवारी"))
            lanlist.add(Languagemodel(language = "Nepali", languagecode = "ne", languagereal = "नेपाली"))
            lanlist.add(Languagemodel(language = "NKo", languagecode = "nqo", languagereal = "N'Ko"))
            lanlist.add(Languagemodel(language = "Norwegian", languagecode = "no", languagereal = "Norsk"))
            lanlist.add(Languagemodel(language = "Nuer", languagecode = "nus", languagereal = "Thuɔŋjäŋ"))
            lanlist.add(Languagemodel(language = "Occitan", languagecode = "oc", languagereal = "Occitan"))
            lanlist.add(Languagemodel(language = "Odia (Oriya)", languagecode = "or", languagereal = "ଓଡ଼ିଆ"))
            lanlist.add(Languagemodel(language = "Oromo", languagecode = "om", languagereal = "Oromoo"))
            lanlist.add(Languagemodel(language = "Ossetian", languagecode = "os", languagereal = "Ирон æвзаг"))
            lanlist.add(Languagemodel(language = "Pangasinan", languagecode = "pag", languagereal = "Pangasinan"))
            lanlist.add(Languagemodel(language = "Papiamento", languagecode = "pap", languagereal = "Papiamentu"))
            lanlist.add(Languagemodel(language = "Pashto", languagecode = "ps", languagereal = "پښتو"))
            lanlist.add(Languagemodel(language = "Persian", languagecode = "fa", languagereal = "فارسی"))
            lanlist.add(Languagemodel(language = "Polish", languagecode = "pl", languagereal = "Polski"))
            lanlist.add(Languagemodel(language = "Portuguese (Brazil)", languagecode = "pt-BR", languagereal = "Português (Brasil)"))
            lanlist.add(Languagemodel(language = "Portuguese (Portugal)", languagecode = "pt-PT", languagereal = "Português (Portugal)"))
            lanlist.add(Languagemodel(language = "Punjabi (Gurmukhi)", languagecode = "pa", languagereal = "ਪੰਜਾਬੀ"))
            lanlist.add(Languagemodel(language = "Punjabi (Shahmukhi)", languagecode = "pnb", languagereal = "پنجابی"))
            lanlist.add(Languagemodel(language = "Quechua", languagecode = "qu", languagereal = "Runa Simi"))
            lanlist.add(Languagemodel(language = "Qʼeqchiʼ", languagecode = "qce", languagereal = "K'icheʼ"))
            lanlist.add(Languagemodel(language = "Romani", languagecode = "rom", languagereal = "Romani"))
            lanlist.add(Languagemodel(language = "Romanian", languagecode = "ro", languagereal = "Română"))
            lanlist.add(Languagemodel(language = "Rundi", languagecode = "rn", languagereal = "Kirundi"))
            lanlist.add(Languagemodel(language = "Russian", languagecode = "ru", languagereal = "Русский"))
            lanlist.add(Languagemodel(language = "Sami (North)", languagecode = "se", languagereal = "Sámegiella"))
            lanlist.add(Languagemodel(language = "Samoan", languagecode = "sm", languagereal = "Gagana Samoa"))
            lanlist.add(Languagemodel(language = "Sango", languagecode = "sg", languagereal = "Sängö"))
            lanlist.add(Languagemodel(language = "Sanskrit", languagecode = "sa", languagereal = "संस्कृत"))
            lanlist.add(Languagemodel(language = "Santali (Latin)", languagecode = "sat-Latn", languagereal = "Santali"))
            lanlist.add(Languagemodel(language = "Santali (Ol Chiki)", languagecode = "sat", languagereal = "ᱥᱟᱱᱛᱟᱲᱤ"))
            lanlist.add(Languagemodel(language = "Scots Gaelic", languagecode = "gd", languagereal = "Gàidhlig"))
            lanlist.add(Languagemodel(language = "Sepedi", languagecode = "ns", languagereal = "Sepedi"))
            lanlist.add(Languagemodel(language = "Serbian", languagecode = "sr", languagereal = "Српски"))
            lanlist.add(Languagemodel(language = "Sesotho", languagecode = "st", languagereal = "Sesotho"))
            lanlist.add(Languagemodel(language = "Seychellois Creole", languagecode = "crs", languagereal = "Kreol Seselwa"))
            lanlist.add(Languagemodel(language = "Shan", languagecode = "shn", languagereal = "ၽႃႇသႃႇ"))
            lanlist.add(Languagemodel(language = "Shona", languagecode = "sn", languagereal = "ChiShona"))
            lanlist.add(Languagemodel(language = "Sicilian", languagecode = "scn", languagereal = "Sicilianu"))
            lanlist.add(Languagemodel(language = "Silesian", languagecode = "szl", languagereal = "Ślůnski"))
            lanlist.add(Languagemodel(language = "Sindhi", languagecode = "sd", languagereal = "سنڌي"))
            lanlist.add(Languagemodel(language = "Sinhala", languagecode = "si", languagereal = "සිංහල"))
            lanlist.add(Languagemodel(language = "Slovak", languagecode = "sk", languagereal = "Slovenčina"))
            lanlist.add(Languagemodel(language = "Slovenian", languagecode = "sl", languagereal = "Slovenščina"))
            lanlist.add(Languagemodel(language = "Somali", languagecode = "so", languagereal = "Soomaali"))
            lanlist.add(Languagemodel(language = "Spanish", languagecode = "es", languagereal = "Español"))
            lanlist.add(Languagemodel(language = "Sundanese", languagecode = "su", languagereal = "Basa Sunda"))
            lanlist.add(Languagemodel(language = "Susu", languagecode = "sus", languagereal = "Susu"))
            lanlist.add(Languagemodel(language = "Swahili", languagecode = "sw", languagereal = "Kiswahili"))
            lanlist.add(Languagemodel(language = "Swati", languagecode = "ss", languagereal = "siSwati"))
            lanlist.add(Languagemodel(language = "Swedish", languagecode = "sv", languagereal = "Svenska"))
            lanlist.add(Languagemodel(language = "Tahitian", languagecode = "ty", languagereal = "Reo Tahiti"))
            lanlist.add(Languagemodel(language = "Tajik", languagecode = "tg", languagereal = "Тоҷикӣ"))
            lanlist.add(Languagemodel(language = "Tamazight", languagecode = "tzm", languagereal = "ⵜⴰⵎⴰⵣⵉⵖⵜ"))
            lanlist.add(Languagemodel(language = "Tamazight (Tifinagh)", languagecode = "tzm-Tfng", languagereal = "ⵜⴰⵎⴰⵣⵉⵖⵜ"))
            lanlist.add(Languagemodel(language = "Tamil", languagecode = "ta", languagereal = "தமிழ்"))
            lanlist.add(Languagemodel(language = "Tatar", languagecode = "tt", languagereal = "Татар теле"))
            lanlist.add(Languagemodel(language = "Telugu", languagecode = "te", languagereal = "తెలుగు"))
            lanlist.add(Languagemodel(language = "Tetum", languagecode = "tet", languagereal = "Tetum"))
            lanlist.add(Languagemodel(language = "Thai", languagecode = "th", languagereal = "ไทย"))
            lanlist.add(Languagemodel(language = "Tibetan", languagecode = "bo", languagereal = "བོད་ཡིག"))
            lanlist.add(Languagemodel(language = "Tigrinya", languagecode = "ti", languagereal = "ትግርኛ"))
            lanlist.add(Languagemodel(language = "Tiv", languagecode = "tiv", languagereal = "Tiv"))
            lanlist.add(Languagemodel(language = "Tok Pisin", languagecode = "tpi", languagereal = "Tok Pisin"))
            lanlist.add(Languagemodel(language = "Tongan", languagecode = "to", languagereal = "lea faka-Tonga"))
            lanlist.add(Languagemodel(language = "Tshiluba", languagecode = "ts", languagereal = "Tshiluba"))
            lanlist.add(Languagemodel(language = "Tsonga", languagecode = "ts", languagereal = "Xitsonga"))
            lanlist.add(Languagemodel(language = "Tswana", languagecode = "tn", languagereal = "Setswana"))
            lanlist.add(Languagemodel(language = "Tulu", languagecode = "tcy", languagereal = "ತುಳು"))
            lanlist.add(Languagemodel(language = "Tumbuka", languagecode = "tum", languagereal = "Tumbuka"))
            lanlist.add(Languagemodel(language = "Turkish", languagecode = "tr", languagereal = "Türkçe"))
            lanlist.add(Languagemodel(language = "Turkmen", languagecode = "tk", languagereal = "Türkmençe"))
            lanlist.add(Languagemodel(language = "Tuvan", languagecode = "tyv", languagereal = "Тыва дыл"))
            lanlist.add(Languagemodel(language = "Twi", languagecode = "tw", languagereal = "Twi"))
            lanlist.add(Languagemodel(language = "Udmurt", languagecode = "udm", languagereal = "Удмурт"))
            lanlist.add(Languagemodel(language = "Ukrainian", languagecode = "uk", languagereal = "Українська"))
            lanlist.add(Languagemodel(language = "Urdu", languagecode = "ur", languagereal = "اردو"))
            lanlist.add(Languagemodel(language = "Uyghur", languagecode = "ug", languagereal = "ئۇيغۇرچە"))
            lanlist.add(Languagemodel(language = "Uzbek", languagecode = "uz", languagereal = "O'zbekcha"))
            lanlist.add(Languagemodel(language = "Venda", languagecode = "ve", languagereal = "Tshivenḓa"))
            lanlist.add(Languagemodel(language = "Venetian", languagecode = "vec", languagereal = "Vèneto"))
            lanlist.add(Languagemodel(language = "Vietnamese", languagecode = "vi", languagereal = "Tiếng Việt"))
            lanlist.add(Languagemodel(language = "Waray", languagecode = "war", languagereal = "Waray"))
            lanlist.add(Languagemodel(language = "Welsh", languagecode = "cy", languagereal = "Cymraeg"))
            lanlist.add(Languagemodel(language = "Wolof", languagecode = "wo", languagereal = "Wollof"))
            lanlist.add(Languagemodel(language = "Xhosa", languagecode = "xh", languagereal = "isiXhosa"))
            lanlist.add(Languagemodel(language = "Yakut", languagecode = "sah", languagereal = "Саха тыла"))
            lanlist.add(Languagemodel(language = "Yiddish", languagecode = "yi", languagereal = "ייִדיש"))
            lanlist.add(Languagemodel(language = "Yoruba", languagecode = "yo", languagereal = "Yorùbá"))
            lanlist.add(Languagemodel(language = "Yucatec Maya", languagecode = "yua", languagereal = "Mayaʼ Tʼaan"))
            lanlist.add(Languagemodel(language = "Zapotec", languagecode = "zap", languagereal = "Zapoteco"))
            lanlist.add(Languagemodel(language = "history", languagecode = "hist", languagereal = "History"))
            lanlist.add(Languagemodel(language = "Zulu", languagecode = "zu", languagereal = "isiZulu"))




                try {
                lanlist.forEachIndexed { index, Languagemodel ->
                    if (Languagemodel.languagecode == changelang) {
                        lanlist[index] = Languagemodel(Languagemodel.language, true, Languagemodel.languagecode, Languagemodel.languagereal)
                    } else {
                        lanlist[index] = Languagemodel(Languagemodel.language, false, Languagemodel.languagecode, Languagemodel.languagereal)
                    }
                }
                val sortedlanlist = lanlist.sortedBy { it.language.toString() }
                lanlistmu.postValue(lanlist)
            } catch (E: Exception) {
            }

        }
    }
}